### ISSUE TITLE
Need to figure out how to do JWPlayer Analytics

### ISSUE THREAD

**Issue by msb** [uisautomation/media-webapp#164]
This looks promising:
https://support.jwplayer.com/articles/jw-player-analytics-reference

**Comment by abrahammartin** [comment]
After adding support for Google Analytics to the JWPlayer player, this is now using the Google Events API and sending data to Google Analytics about events relating to the player (start, stop, etc). These events are anonymous so if we need to do something more than that then we'd need to start looking for an additional solution like segment.

Also worth mentioning that this is not super rich data but just the basics and that jwplayer contains way more useful information in their web backend. Unfortunately doesn't look like we can extract this data using an API. I suggest to look at "Content" in the "Analyze" section for ilustration.
