### ISSUE TITLE
Attempt to re-upload broken videos

### ISSUE THREAD

**Issue by rjw57** [uisautomation/media-webapp#225]
We now have a breakdown of video transcode fails available in https://github.com/uisautomation/sms2jwplayer/issues/29. Write a small script to re-upload the videos and see if this improves. Another possibility is deleting the troublesome videos from JWP and letting sms2jwp re-upload them. Deleting the troublesome videos is probably the easiest option.

**Comment by abrahammartin** [comment]
I attempted to re-upload all the videos and all of them failed again. Checking with jwplayer to know why they failed.

**Comment by msb** [comment]
I used the following SQL to extract data on the corrupted clips (for both the SMS and JW keys):

```sql
COPY (
    SELECT data->'custom'->'sms_media_id', data->'custom'->'sms_clip_id', mediaplatform_jwp_video.key jw_key
    FROM mediaplatform_jwp_cachedresource
    JOIN mediaplatform_jwp_video ON mediaplatform_jwp_video.resource_id = mediaplatform_jwp_cachedresource.key
    WHERE data->'status' ? 'failed' AND deleted_at is NULL
) To STDOUT With CSV DELIMITER ',';
```

**Comment by msb** [comment]
At the end of this process 7 clips were failing. These were investigated as follows (identified by their media id and title):

- 1849267 (minimal black) - don't play on sms either
- 1849404 (minimal white) - don't play on sms either
- 1205209 (Bumper) - don't play on sms either
- 2458748 (Adjoint-based stabilization of a thermoacoustic network model) - only about 1 second long
- 2416238 (Hidden Toy - B101) - extremely poor quality
- 2416270 (Hidden Toy - B104) - extremely poor quality
- 2417976 (Hidden Toy - M112) - extremely poor quality

**Comment by rjw57** [comment]
Tried a selection of the videos from the original CSV, seemed to work.
