### ISSUE TITLE
Add embed and download views and re-write legacysms views to use them

### ISSUE THREAD

**Issue by rjw57** [uisautomation/media-webapp#228]
Rather than directly including JWP embed and download links in the API, we should form our own which are not time limited (but, obviously, still check for access). We can then redirect to them from the legacysms embed and download views rather than relying on the somewhat crusty old code we currently have there.

**Comment by abrahammartin** [comment]
Done in #238 ?

**Comment by abrahammartin** [comment]
This is done now
