### ISSUE TITLE
Download a copy of all transcoded videos from JWPlayer

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/media-webapp#315]
> See also: #259 and #305

Create a cronjob in one of the SMS storage boxes to download all transcodes of each JWPlayer video. This will allow us to have a cache of everything in case something happens with our online provider. Make sure you use the SMS storage box that is rsynced into the HPC backups.

Check if we have enough storage left for the sync in our current HPC backup tape, if not, poke amc203.

Make it a cronjob so it executes periodically and downloads all the resources that haven't been cached before.

**Comment by rjw57** [comment]
This script should do the following:

- Scan all media items via the API in order of decreasing updatedAt
- For each updated media item with id of the form ABCDEFGH, create a directory AB/CD to store the item in. Create AB/CD/DEFGH.json which is the resource.
- If a source is available for the media item and it is not yet downloaded, download the source to AB/CD/DEFGH.mp4
