### ISSUE TITLE
Embeddable playlist view

### ISSUE THREAD

**Issue by rjw57** [uisautomation/media-webapp#359]
Add an embedded playlist view. The JWPlayer HTML5 player supports playlists so we can simply use this. Add a UI view /playlists/{key}/embed which works like /media/{key}/embed. 

This is required so that we can embed lecture courses into a Moodle page.

**This is unrelated to JWPlayform's playlist support.**

See also: JWPlayer playlist demo https://developer.jwplayer.com/jw-player/demos/basic/loading-new-playlists/.

**Comment by abrahammartin** [comment]
I'm unassigning me the task as I didn't have time to start it last Friday and I'm already committed for the rest of the sprint.

**Comment by abrahammartin** [comment]
@rjw57 this done now by #405, no?

**Comment by rjw57** [comment]
Yup.
