### ISSUE TITLE
Consume and add videos from OAI-PMH Opencast feed

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/media-webapp#393]
Make the Media Platform to consume the resources from the OAI-PMH Opencast feed. Add the missing/new videos to the platform. Pull periodically. The Media Platform will probably have to wait for the videos to be distributed (after they are published). Definition of published/distributed by James from Manchester:

* Publication is making the Mediapackage metadata available eg storing in the Engage search index, or making available as an OAIPMH record. 
* Distribution is making the contents of the Mediapackage available, this is the media as well as the Dublincore catalogs for the episode and series. In addition there may be images, extracted text and captions. Engage and OAIPMH both use the DownloadDistributionService dir and url that you specify in the custom.properties. For us this is location of our NFS filesystem which is mounted by our download servers.

**Comment by rjw57** [comment]
Closed by #396
