### ISSUE TITLE
LC8: Include a subtitles flag in media items

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/media-webapp#403]
We want to include a flag in the MediaItem class that would indicate us if we need to generate subtitles (audio transcriptions) for that media item. ~~This will be on by default for some pre-selected lecture capture series.~~

**Comment by rjw57** [comment]
This flag is essentially used to record that it is requested that a recording be transcribed. This is not a core media item property so I suggest this is done via a new model and, perhaps, a new application.
```python
class TranscriptionRequest(models.Model):
    media_item = models.ForeignKey('mediaplatform.MediaItem')
    # ... plus usual {created,updated}_at fields
```
Until we actually have a transcription service, I suggest this suffices. We may then update the OAIPMH application to create a request for each ingested video and we can create some manual ones to test.

**Comment by rjw57** [comment]
> This will be on by default for some pre-selected lecture capture series.

Now tracked in #419
